fix: Use CONSUL_HTTP_ADDR environment variable instead of invalid Address() method
The Consul API client doesn't have an Address() method in the version we're using.
Changed debug logging to use os.Getenv("CONSUL_HTTP_ADDR") instead.

This fixes the compilation error in CI:
./main.go:32:38: env.ConsulClient.Address undefined (type *api.Client has no field or method Address)